# Generated by Django 5.2.17 on 2026-09-28 06:29

import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.db.models.lookups
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMeta',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
            ],
            options={
                'db_table': 'app_meta',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('username_key', models.CharField(max_length=64, unique=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('auth_version', models.PositiveIntegerField(default=1)),
                ('deleting', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('account', 'account'), ('source', 'source')], max_length=7)),
                ('key', models.TextField()),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_limits',
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='login_limits_scope_key_unique'), models.CheckConstraint(condition=models.Q(('scope__in', ['account', 'source'])), name='login_limits_scope_valid'), models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('key'))), models.Value(0)), name='login_limits_key_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=7)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('hidden', 'hidden')], max_length=6)),
                ('original_author', models.CharField(max_length=255)),
                ('rule_name', models.CharField(max_length=128)),
                ('config_json', models.JSONField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pools',
            },
        ),
        migrations.CreateModel(
            name='ExperimentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
                ('pool_name_hint', models.CharField(blank=True, max_length=255)),
                ('parameters_json', models.JSONField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_configs', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_configs', to='dashboard.pool')),
            ],
            options={
                'db_table': 'experiment_configs',
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool_id_snapshot', models.UUIDField()),
                ('pool_revision_snapshot', models.PositiveIntegerField()),
                ('pool_name_snapshot', models.CharField(max_length=255)),
                ('original_author_snapshot', models.CharField(max_length=255)),
                ('rule_name', models.CharField(max_length=128)),
                ('rule_version', models.CharField(max_length=32)),
                ('main_draws', models.PositiveIntegerField()),
                ('trials', models.PositiveIntegerField()),
                ('initial_pity', models.PositiveIntegerField()),
                ('initial_five_star_pity', models.PositiveIntegerField()),
                ('seed', models.TextField()),
                ('trace_enabled', models.BooleanField()),
                ('record_count', models.PositiveIntegerField()),
                ('pool_config_json', models.JSONField()),
                ('result_json', models.JSONField()),
                ('schema_version', models.PositiveSmallIntegerField(default=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simulation_runs',
            },
        ),
        migrations.CreateModel(
            name='DrawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_index', models.PositiveIntegerField()),
                ('draw_index', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('main', 'main'), ('bonus', 'bonus')], max_length=5)),
                ('source_index', models.PositiveIntegerField()),
                ('rarity', models.PositiveSmallIntegerField(choices=[(4, '4'), (5, '5'), (6, '6')])),
                ('character_name', models.TextField(blank=True, null=True)),
                ('record_json', models.JSONField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_records', to='dashboard.simulationrun')),
            ],
            options={
                'db_table': 'draw_records',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('username'))), models.Value(0)), name='users_username_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('username_key'))), models.Value(0)), name='users_username_key_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_staff', models.F('is_superuser'))), name='users_staff_matches_superuser'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'public'), ('owner__isnull', True), ('visibility', 'public')), models.Q(('kind', 'private'), ('owner__isnull', False), ('visibility__in', ['public', 'hidden'])), _connector='OR'), name='pools_kind_owner_visibility'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('name'))), models.Value(0)), name='pools_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('name_key'))), models.Value(0)), name='pools_name_key_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='pools_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'public')), fields=('name_key',), name='pools_public_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'private')), fields=('owner', 'name_key'), name='pools_private_owner_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='experimentconfig',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('name'))), models.Value(0)), name='experiment_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='experimentconfig',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim(models.F('name_key'))), models.Value(0)), name='experiment_name_key_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='experimentconfig',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='experiment_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='experimentconfig',
            constraint=models.UniqueConstraint(fields=('owner', 'name_key'), name='experiment_owner_name_unique'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['owner', '-created_at'], name='runs_owner_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version', 5)), name='runs_schema_version_v5'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.CheckConstraint(condition=models.Q(('pool_revision_snapshot__gte', 1)), name='runs_pool_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.CheckConstraint(condition=models.Q(('main_draws__gte', 1), ('trials__gte', 1)), name='runs_draw_counts_positive'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('record_count', 0), ('trace_enabled', False)), models.Q(('record_count__gt', 0), ('trace_enabled', True)), _connector='OR'), name='runs_trace_count_matches'),
        ),
        migrations.AddIndex(
            model_name='drawrecord',
            index=models.Index(fields=['run', 'source', 'source_index', 'rarity'], name='draw_run_source_position_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawrecord',
            constraint=models.UniqueConstraint(fields=('run', 'trial_index', 'draw_index'), name='draw_records_run_trial_draw_unique'),
        ),
        migrations.AddConstraint(
            model_name='drawrecord',
            constraint=models.CheckConstraint(condition=models.Q(('draw_index__gt', 0), ('source_index__gt', 0), ('trial_index__gt', 0)), name='draw_records_indexes_positive'),
        ),
        migrations.AddConstraint(
            model_name='drawrecord',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['main', 'bonus'])), name='draw_records_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='drawrecord',
            constraint=models.CheckConstraint(condition=models.Q(('rarity__in', [4, 5, 6])), name='draw_records_rarity_valid'),
        ),
        migrations.AddConstraint(
            model_name='drawrecord',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.RawSQL("json_type(record_json, '$') IS 'object' AND json_type(record_json, '$.record_format_version') IS 'integer' AND json_extract(record_json, '$.record_format_version') = 2 AND trial_index IS json_extract(record_json, '$.trial_index') AND draw_index IS json_extract(record_json, '$.draw_index') AND source IS json_extract(record_json, '$.source') AND source_index IS json_extract(record_json, '$.source_index') AND rarity IS json_extract(record_json, '$.draw_result.outcome.rarity') AND character_name IS json_extract(record_json, '$.draw_result.outcome.character_name')", [], output_field=models.BooleanField()), name='draw_records_json_matches_columns'),
        ),
        # Django's on_delete is an ORM collector policy; SQLite emits NO ACTION.
        # Keep the same behavior for the task-7 parameterized SQL path as well.
        migrations.RunSQL(
            "CREATE TRIGGER pools_config_set_null AFTER DELETE ON pools "
            "BEGIN UPDATE experiment_configs SET pool_id = NULL WHERE pool_id = OLD.id; END",
            "DROP TRIGGER pools_config_set_null",
        ),
        migrations.RunSQL(
            "CREATE TRIGGER runs_draw_records_cascade AFTER DELETE ON simulation_runs "
            "BEGIN DELETE FROM draw_records WHERE run_id = OLD.id; END",
            "DROP TRIGGER runs_draw_records_cascade",
        ),
        migrations.RunSQL("PRAGMA user_version = 5", "PRAGMA user_version = 0"),
    ]
